### ISSUE TITLE
GroupId

### ISSUE THREAD

**Issue by suntchan** [pierrekilly/docker-ros-box#1]
Bonjour Pierre,

Et merci pour ce docker, je débute avec ROS et cela va me permettre de démarrer rapidement sous Manjaro!

Il y a un petit problème dans ton Dockerfile, remplacer uid par gid dans 

echo "${ros_distro}-dev:x:${uid}:" >> /etc/group devient
echo "${ros_distro}-dev:x:${gid}:" >> /etc/group

Frédéric

**Comment by pierrekilly** [comment]
Hello @suntchan! Tu as tout à fait raison, je viens de corriger!

Merci :D
